"""add queue counters

Revision ID: 0fe6f0480999
Revises: 21778b4a321d
Create Date: 2026-10-04 17:12:11.248959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe6f0480999'
down_revision: Union[str, Sequence[str], None] = '21778b4a321d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_entries', sa.Column('counter_number', sa.Integer(), nullable=True))
    op.add_column('queues', sa.Column('counter_count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'counter_count')
    op.drop_column('queue_entries', 'counter_number')
    # ### end Alembic commands ###
