"""add cover_image to users

Revision ID: bdfca3ce0d5f
Revises: 0fe6f0480999
Create Date: 2026-10-05 08:39:31.482180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfca3ce0d5f'
down_revision: Union[str, Sequence[str], None] = '0fe6f0480999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_image')
    # ### end Alembic commands ###
