"""Add optional queue assignment to staff

Revision ID: c834ee646974
Revises: eda56c463588
Create Date: 2026-10-06 20:05:36.096147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c834ee646974'
down_revision: Union[str, Sequence[str], None] = 'eda56c463588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('queue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staff', 'queues', ['queue_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'queue_id')
    # ### end Alembic commands ###
