"""add counter number to staff

Revision ID: eda56c463588
Revises: bdfca3ce0d5f
Create Date: 2026-10-06 09:59:53.356278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda56c463588'
down_revision: Union[str, Sequence[str], None] = 'bdfca3ce0d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('counter_number', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'counter_number')
    # ### end Alembic commands ###
